### PR TITLE
Added new 1.4.6 version of log4javascript with working package.json to use it in npm

### PR DESCRIPTION
**Pull request by mikelohmann**
Now you can add 
"dependencies": {
    "node-uuid": "1.4.x",
    "log4javascript": "git+https://github.com/DECK36/log4javascript.git#v1.4.6"
  },
to your package.json Dependencies.

### CODE REVIEW

**Comment by owain** [comment]
Thank you for the PR. Please accept my apologies for not reviewing this any earlier. 

Unfortunately this repo is no longer used by us and has been unmaintained for a while (as you've seen). The best thing for everyone is to let someone else take over maintaining the clone to ensure it's kept up to date.

@pavlo-yuriychuk & @mikelohmann - you've both submitted PR's (#1, #3) to update the repo. Would either of you have interest in taking control of the repo? We can transfer ownership to you.

**Comment by mikelohmann** [comment]
Hi,

For us it is really important. So I am interested in taking the responsibilty.

Ok for you, Pavlo?

Thanks for the offer.

Regards

Mike
—

**Comment by pavlo-yuriychuk** [comment]
Hello Mike,

I am fine with that, let me know if I can help you.

2014-02-26 22:25 GMT+02:00 Mike Lohmann notifications@github.com:

**Comment by owain** [comment]
Looks like log4javascript has a new home. :) Thanks @mikelohmann

**Pull request merged**
